
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1
mod_id=createfastschematiccannon
mod_name=Create: Fast Schematic Cannon
package_name = CreateFastSchematicCannon
display_name = CFC
publish_version = release

mod_license=MIT
mod_version=1.4-neoforge
mod_group_id=com.Pink_Cats
mod_authors=Pink_Cats
mod_description=A mod for make schematic cannon more fast and fix cannon delay from server.

mixin_version = 0.8.5
cc_tweaked_enable = false
cc_tweaked_minecraft_version = 1.20.1
cc_tweaked_version = 1.105.0

ct_enabled = true
ct_minecraft_version = 1.20.1
ct_version = 14.0.17
ct_annotation_processor_version = 3.0.0.15
ct_create_version =  4.0.15
ct_create_id = 4548572

# other version
create_version = 6.0.6-98
ponder_version = 1.0.56
flywheel_version = 1.0.4
registrate_version = MC1.21-1.3.0+62
jei_version=19.21.2.313

# base
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.209
neo_version_range=[21,)
loader_version_range=[4,)

# dependency versions
jei_minecraft_version = 1.20.1
curios_minecraft_version = 1.20.1
curios_version = 5.3.1

jade_id = 6106101
architectury_version=9.1.12
rhino_version=2001.2.3-build.10
kubejs_version=2001.6.5-build.17
mixin_extras_version = 0.4.1

parchment_version = 2023.06.26
forge_version=47.4.8
forge_version_range=[47,)
curseforge_id =1352204
modrinth_id =DebMSCVn

# create
# dependency versions
flywheel_minecraft_version = 1.20.1
org.gradle.configureondemand=true
org.gradle.logging.level=quiet

# gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true