modLoader = "javafml" #mandatory
loaderVersion = "[40,)"
license = "MIT"


[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    logoFile="icon.png"
    version = "${mod_version}" #mandatory
    displayName = "${mod_name}" #mandatory
    authors = "${mod_authors}" #optional
    description = '''${mod_description}'''


[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"


[[dependencies."${mod_id}"]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,0.5.2)"
    ordering="NONE"
    side="BOTH"

